name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-checks:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        test-os: [ubuntu-latest]

    runs-on: ${{ matrix.test-os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Install test dependencies
        run: pip install -r script/requirements-dev.txt

      - name: Lint
        run: ./script/linting/lint

      - name: Typecheck
        run: ./script/typing/check

      - name: Test
        run: ./run-tests

  action-check:
    strategy:
      matrix:
        test-os: [ubuntu-latest]

    runs-on: ${{ matrix.test-os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          echo foo > /tmp/foo.out
          echo bar > /tmp/bar.out
          echo baz > /tmp/baz.out

      - name: Happy path
        uses: ./.
        with:
          command: python -c "print('foo', file=open('/tmp/foo.out', mode='w')); print('bar', file=open('/tmp/bar.out', mode='w'))"
          files: |
            /tmp/foo.out
            /tmp/ba*.out

      - name: Mismatch in wildcard file
        uses: ./.
        continue-on-error: true
        id: should-fail
        with:
          command: python -c "print('BAR', file=open('/tmp/baz.out', mode='w'))"
          files: |
            /tmp/foo.out
            /tmp/ba*.out

      - name: Check expected failure
        if: ${{ steps.should-fail.outcome != 'failure' }}
        run: |
          echo "Unexpected outcome from mismatched files: ${{ steps.should-fail.outcome }} != failure"
          exit 1
